import {MigrationInterface, QueryRunner} from "typeorm";

export class MovieMigration31611495311725 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        queryRunner.query(`

INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,128.612,54,'Thor is imprisoned on the other side of the universe and finds himself in a race against time to get back to Asgard to stop Ragnarok\, the destruction of his home-world and the end of Asgardian civilization\, at the hands of an all-powerful new threat\, the ruthless Hela.',false,'Thor: Ragnarok','https://image.tmdb.org/t/p/w300/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg','[{\"id\":28\,\"name\":\"Action\"}\,{\"id\":12\,\"name\":\"Adventure\"}\,{\"id\":35\,\"name\":\"Comedy\"}\,{\"id\":14\,\"name\":\"Fantasy\"}\,{\"id\":878\,\"name\":\"Science Fiction\"}]','2017-10-25',7.6,15250);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,128.255,53,'Half a year after the events of the series \"Kabaneri of the Iron Fortress\"\, the team attempt to take back Unato castle.',false,'甲鉄城のカバネリ～海門決戦～','https://image.tmdb.org/t/p/w300/6t1esuYHkOFO5SejAVFlu6alChr.jpg','[{\"id\":16\,\"name\":\"Animation\"}\,{\"id\":28\,\"name\":\"Action\"}\,{\"id\":14\,\"name\":\"Fantasy\"}\,{\"id\":12\,\"name\":\"Adventure\"}]','2019-05-10',7.2,24);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,127.742,34,'After waking up with mysterious wounds on his hands\, a champion fighter finds himself in an otherworldly battle against evil forces that wreak havoc in the human world.',false,'사자','https://image.tmdb.org/t/p/w300/9Z2qT9iZYLzzsCSYu7A4SEQsKX0.jpg','[{\"id\":28\,\"name\":\"Action\"}\,{\"id\":27\,\"name\":\"Horror\"}]','2019-07-31',6.2,133);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,127.219,49,'Following the events of Captain America: Civil War\, Peter Parker\, with the help of his mentor Tony Stark\, tries to balance his life as an ordinary high school student in Queens\, New York City\, with fighting crime as his superhero alter ego Spider-Man as a new threat\, the Vulture\, emerges.',false,'Spider-Man: Homecoming','https://image.tmdb.org/t/p/w300/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg','[{\"id\":28\,\"name\":\"Action\"}\,{\"id\":12\,\"name\":\"Adventure\"}\,{\"id\":878\,\"name\":\"Science Fiction\"}\,{\"id\":18\,\"name\":\"Drama\"}]','2017-07-05',7.4,15486);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,126.433,36,'An intelligent 15-year-old high school student is unexpectedly transferred to a boarding school where he opens a portal of monsters from another dimension.',false,'Cranston Academy: Monster Zone','https://image.tmdb.org/t/p/w300/iwWDHYlmiOXNBCsvhCDfccluLQK.jpg','[{\"id\":16\,\"name\":\"Animation\"}]','2020-04-29',6.6,44);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,125.866,13,'Rikka is a ninja descendant. Her grandfather Hyoe is the last chief of their ninja clan and her father is a cyborg researcher. Both are killed when a weapons'' company raids his lab to use his research. Rikka sets out to avenge their deaths.',false,'Blackfox','https://image.tmdb.org/t/p/w300/7ypOmAQ3TowBa4iBILBboOEQqYh.jpg','[{\"id\":16\,\"name\":\"Animation\"}\,{\"id\":28\,\"name\":\"Action\"}\,{\"id\":18\,\"name\":\"Drama\"}\,{\"id\":878\,\"name\":\"Science Fiction\"}]','2019-10-05',7.7,13);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,125.03,33,'Kate Pierce is reluctantly spending Christmas with her mom’s new boyfriend and his son Jack. But when the North Pole and Christmas are threatened to be destroyed\, Kate and Jack are unexpectedly pulled into a new adventure with Santa Claus.',false,'The Christmas Chronicles: Part Two','https://image.tmdb.org/t/p/w300/6sG0kbEvAi3RRLcGGU5h8l3qAPa.jpg','[{\"id\":10751\,\"name\":\"Family\"}\,{\"id\":14\,\"name\":\"Fantasy\"}\,{\"id\":12\,\"name\":\"Adventure\"}\,{\"id\":35\,\"name\":\"Comedy\"}]','2020-11-18',6.6,533);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,124.261,76,'Cars fly\, trees fight back\, and a mysterious house-elf comes to warn Harry Potter at the start of his second year at Hogwarts. Adventure and danger await when bloody writing on a wall announces: The Chamber Of Secrets Has Been Opened. To save Hogwarts will require all of Harry\, Ron and Hermione’s magical abilities and courage.',false,'Harry Potter and the Chamber of Secrets','https://image.tmdb.org/t/p/w300/sdEOH0992YZ0QSxgXNIGLq1ToUi.jpg','[{\"id\":12\,\"name\":\"Adventure\"}\,{\"id\":14\,\"name\":\"Fantasy\"}]','2002-11-13',7.7,15788);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,124.244,71,'As Harry begins his sixth year at Hogwarts\, he discovers an old book marked as ''Property of the Half-Blood Prince''\, and begins to learn more about Lord Voldemort''s dark past.',false,'Harry Potter and the Half-Blood Prince','https://image.tmdb.org/t/p/w300/z7uo9zmQdQwU5ZJHFpv2Upl30i1.jpg','[{\"id\":12\,\"name\":\"Adventure\"}\,{\"id\":14\,\"name\":\"Fantasy\"}]','2009-07-07',7.7,14021);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,123.925,34,'In a time when monsters walk the Earth\, humanity’s fight for its future sets Godzilla and Kong on a collision course that will see the two most powerful forces of nature on the planet collide in a spectacular battle for the ages.',false,'Godzilla vs. Kong','https://image.tmdb.org/t/p/w300/aU3csT4w0QEdpi4pnh7IunsaMw0.jpg','[{\"id\":28\,\"name\":\"Action\"}\,{\"id\":878\,\"name\":\"Science Fiction\"}]','2021-03-25',0,0);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,123.136,97,'Set in a post-apocalyptic world\, young Thomas is deposited in a community of boys after his memory is erased\, soon learning they''re all trapped in a maze that will require him to join forces with fellow “runners” for a shot at escape.',false,'The Maze Runner','https://image.tmdb.org/t/p/w300/ode14q7WtDugFDp78fo9lCsmay9.jpg','[{\"id\":28\,\"name\":\"Action\"}\,{\"id\":9648\,\"name\":\"Mystery\"}\,{\"id\":878\,\"name\":\"Science Fiction\"}\,{\"id\":53\,\"name\":\"Thriller\"}]','2014-09-10',7.1,12994);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,123.076,74,'Three years after the demise of Jurassic World\, a volcanic eruption threatens the remaining dinosaurs on the isla Nublar\, so Claire Dearing\, the former park manager\, recruits Owen Grady to help prevent the extinction of the dinosaurs once again.',false,'Jurassic World: Fallen Kingdom','https://image.tmdb.org/t/p/w300/c9XxwwhPHdaImA2f1WEfEsbhaFB.jpg','[{\"id\":28\,\"name\":\"Action\"}\,{\"id\":12\,\"name\":\"Adventure\"}\,{\"id\":878\,\"name\":\"Science Fiction\"}]','2018-06-06',6.6,8552);
INSERT INTO movie (wish_list, popularity, price, overview, adult, original_title, poster, genres, release_date, vote_average, vote_count) VALUES (false,117.625,45,'Set in the African savannah\, the film follows Kion as he assembles the members of the ''Lion Guard''. Throughout the film\, the diverse team of young animals will learn how to utilize each of their unique abilities to solve problems and accomplish tasks to maintain balance within the Circle of Life\, while also introducing viewers to the vast array of animals that populate the prodigious African landscape.',false,'The Lion Guard: Return of the Roar','https://image.tmdb.org/t/p/w300/duqg6CiSik02nSXjiQHo8TcwY4b.jpg','[{\"id\":10770\,\"name\":\"TV Movie\"}\,{\"id\":16\,\"name\":\"Animation\"}\,{\"id\":10751\,\"name\":\"Family\"}]','2015-11-22',6.1,198);

     
        `)
    }

    public async down(_: QueryRunner): Promise<void> {
    }

}
